---
id: Smtp
name: Smtp
full: SMTP client library
description: A library for connecting to a SMTP (RFC 5321) server to send e-mail messages.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha2
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/mail: ^3
      horde/socket_client: ^3
      horde/support: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/imap_client: ^3
      horde/secret: ^3
      horde/test: ^3
